spring:
  datasource:
    url: jdbc:sqlserver://team-mpp-sql-server.database.windows.net:1433;database=FoodApplication;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: TeamMppAdmin
    password: CloudProject3
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2016Dialect
  flyway:
    enabled: false
    validate-on-migrate: true

